"""add label to cards

Revision ID: 034101a3d975
Revises: 25ce00c3d881
Create Date: 2026-03-01 01:19:20.521524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '034101a3d975'
down_revision: Union[str, Sequence[str], None] = '25ce00c3d881'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False), schema='finance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'label', schema='finance')
    # ### end Alembic commands ###
