"""Criando model cards

Revision ID: 25ce00c3d881
Revises: 70aaa383cb25
Create Date: 2026-03-01 00:03:51.147022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '25ce00c3d881'
down_revision: Union[str, Sequence[str], None] = '70aaa383cb25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('flag', sa.Enum('mastercard', 'visa', name='cardflag'), nullable=False),
    sa.Column('close_day', sa.Integer(), nullable=False),
    sa.Column('due_day', sa.Integer(), nullable=False),
    sa.Column('limit', sa.Float(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['finance.accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='finance'
    )
    op.create_index(op.f('ix_finance_cards_account_id'), 'cards', ['account_id'], unique=False, schema='finance')
    op.create_index(op.f('ix_finance_cards_id'), 'cards', ['id'], unique=False, schema='finance')
    op.create_index(op.f('ix_finance_cards_user_id'), 'cards', ['user_id'], unique=False, schema='finance')
    op.add_column('transactions', sa.Column('card_id', sa.Uuid(), nullable=True), schema='finance')
    op.create_index(op.f('ix_finance_transactions_card_id'), 'transactions', ['card_id'], unique=False, schema='finance')
    op.create_foreign_key(None, 'transactions', 'cards', ['card_id'], ['id'], source_schema='finance', referent_schema='finance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', schema='finance', type_='foreignkey')
    op.drop_index(op.f('ix_finance_transactions_card_id'), table_name='transactions', schema='finance')
    op.drop_column('transactions', 'card_id', schema='finance')
    op.drop_index(op.f('ix_finance_cards_user_id'), table_name='cards', schema='finance')
    op.drop_index(op.f('ix_finance_cards_id'), table_name='cards', schema='finance')
    op.drop_index(op.f('ix_finance_cards_account_id'), table_name='cards', schema='finance')
    op.drop_table('cards', schema='finance')
    # ### end Alembic commands ###
