"""Atualizando models

Revision ID: 70aaa383cb25
Revises: acddee5c9409
Create Date: 2026-02-28 16:20:11.595918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '70aaa383cb25'
down_revision: Union[str, Sequence[str], None] = 'acddee5c9409'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('FIAT', 'CRIPTO', name='currencytype'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='finance'
    )
    op.create_index(op.f('ix_finance_currencies_id'), 'currencies', ['id'], unique=False, schema='finance')
    op.create_index(op.f('ix_finance_currencies_label'), 'currencies', ['label'], unique=False, schema='finance')
    op.create_index(op.f('ix_finance_currencies_symbol'), 'currencies', ['symbol'], unique=False, schema='finance')
    op.create_index('unique_currency_label_symbol', 'currencies', ['label', 'symbol'], unique=True, schema='finance')
    op.create_table('financial_institutions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('BANK', 'FINTECH', 'BROKER', 'EXCHANGE', 'WALLET', name='institutiontype'), nullable=False),
    sa.Column('icon_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'type', name='uq_financial_institutions_name_type'),
    schema='finance'
    )
    op.create_index(op.f('ix_finance_financial_institutions_id'), 'financial_institutions', ['id'], unique=False, schema='finance')
    op.create_index(op.f('ix_finance_financial_institutions_name'), 'financial_institutions', ['name'], unique=False, schema='finance')
    op.create_table('accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('financial_institution_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('activate', 'deactivate', name='accountstatus'), nullable=False),
    sa.Column('type', sa.Enum('bank', 'investment', 'cash', 'benefit', name='accounttype'), nullable=False),
    sa.Column('subtype', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['financial_institution_id'], ['finance.financial_institutions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='finance'
    )
    op.create_index(op.f('ix_finance_accounts_financial_institution_id'), 'accounts', ['financial_institution_id'], unique=False, schema='finance')
    op.create_index(op.f('ix_finance_accounts_id'), 'accounts', ['id'], unique=False, schema='finance')
    op.create_index('unique_account_null_subtype', 'accounts', ['user_id', 'financial_institution_id', 'type'], unique=True, schema='finance', postgresql_where=sa.text('subtype IS NULL'))
    op.create_index('unique_account_with_subtype', 'accounts', ['user_id', 'financial_institution_id', 'type', 'subtype'], unique=True, schema='finance', postgresql_where=sa.text('subtype IS NOT NULL'))
    op.create_table('categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('OUTCOME', 'INCOME', name='categorytype'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'label', 'type', name='uq_finance_categories'),
    schema='finance'
    )
    op.create_index(op.f('ix_finance_categories_id'), 'categories', ['id'], unique=False, schema='finance')
    op.create_index(op.f('ix_finance_categories_label'), 'categories', ['label'], unique=False, schema='finance')
    op.create_index(op.f('ix_finance_categories_user_id'), 'categories', ['user_id'], unique=False, schema='finance')
    op.create_table('payment_methods',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='finance'
    )
    op.create_index(op.f('ix_finance_payment_methods_id'), 'payment_methods', ['id'], unique=False, schema='finance')
    op.create_index(op.f('ix_finance_payment_methods_label'), 'payment_methods', ['label'], unique=False, schema='finance')
    op.create_index(op.f('ix_finance_payment_methods_user_id'), 'payment_methods', ['user_id'], unique=False, schema='finance')
    op.create_index('payment_method_idx', 'payment_methods', ['user_id', 'label'], unique=True, schema='finance')
    op.create_table('subcategories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['finance.categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'label', name='uq_finance_subcategory'),
    schema='finance'
    )
    op.create_index(op.f('ix_finance_subcategories_category_id'), 'subcategories', ['category_id'], unique=False, schema='finance')
    op.create_index(op.f('ix_finance_subcategories_id'), 'subcategories', ['id'], unique=False, schema='finance')
    op.create_index(op.f('ix_finance_subcategories_label'), 'subcategories', ['label'], unique=False, schema='finance')
    op.create_table('tags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('subcategory_id', sa.Uuid(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['finance.categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['finance.subcategories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category_id', 'subcategory_id', name='uq_finance_tag'),
    schema='finance'
    )
    op.create_index(op.f('ix_finance_tags_id'), 'tags', ['id'], unique=False, schema='finance')
    op.create_index(op.f('ix_finance_tags_user_id'), 'tags', ['user_id'], unique=False, schema='finance')
    op.create_table('transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.Column('payment_method_id', sa.Uuid(), nullable=False),
    sa.Column('currency_id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=False),
    sa.Column('date_transaction', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['finance.accounts.id'], ),
    sa.ForeignKeyConstraint(['currency_id'], ['finance.currencies.id'], ),
    sa.ForeignKeyConstraint(['payment_method_id'], ['finance.payment_methods.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['finance.tags.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='finance'
    )
    op.create_index(op.f('ix_finance_transactions_account_id'), 'transactions', ['account_id'], unique=False, schema='finance')
    op.create_index(op.f('ix_finance_transactions_id'), 'transactions', ['id'], unique=False, schema='finance')
    op.create_index(op.f('ix_finance_transactions_payment_method_id'), 'transactions', ['payment_method_id'], unique=False, schema='finance')
    op.create_index(op.f('ix_finance_transactions_tag_id'), 'transactions', ['tag_id'], unique=False, schema='finance')
    op.create_index(op.f('ix_finance_transactions_user_id'), 'transactions', ['user_id'], unique=False, schema='finance')
    op.create_table('holdings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('asset_type', sa.Enum('CRIPTO', 'STOCK', 'ETF', 'BOND', name='assettype'), nullable=False),
    sa.Column('quantity', sa.Numeric(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['finance.transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='finance'
    )
    op.create_index(op.f('ix_finance_holdings_id'), 'holdings', ['id'], unique=False, schema='finance')
    op.create_index(op.f('ix_finance_holdings_symbol'), 'holdings', ['symbol'], unique=False, schema='finance')
    op.create_index(op.f('ix_finance_holdings_transaction_id'), 'holdings', ['transaction_id'], unique=False, schema='finance')
    op.create_index(op.f('ix_finance_holdings_user_id'), 'holdings', ['user_id'], unique=False, schema='finance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_finance_holdings_user_id'), table_name='holdings', schema='finance')
    op.drop_index(op.f('ix_finance_holdings_transaction_id'), table_name='holdings', schema='finance')
    op.drop_index(op.f('ix_finance_holdings_symbol'), table_name='holdings', schema='finance')
    op.drop_index(op.f('ix_finance_holdings_id'), table_name='holdings', schema='finance')
    op.drop_table('holdings', schema='finance')
    op.drop_index(op.f('ix_finance_transactions_user_id'), table_name='transactions', schema='finance')
    op.drop_index(op.f('ix_finance_transactions_tag_id'), table_name='transactions', schema='finance')
    op.drop_index(op.f('ix_finance_transactions_payment_method_id'), table_name='transactions', schema='finance')
    op.drop_index(op.f('ix_finance_transactions_id'), table_name='transactions', schema='finance')
    op.drop_index(op.f('ix_finance_transactions_account_id'), table_name='transactions', schema='finance')
    op.drop_table('transactions', schema='finance')
    op.drop_index(op.f('ix_finance_tags_user_id'), table_name='tags', schema='finance')
    op.drop_index(op.f('ix_finance_tags_id'), table_name='tags', schema='finance')
    op.drop_table('tags', schema='finance')
    op.drop_index(op.f('ix_finance_subcategories_label'), table_name='subcategories', schema='finance')
    op.drop_index(op.f('ix_finance_subcategories_id'), table_name='subcategories', schema='finance')
    op.drop_index(op.f('ix_finance_subcategories_category_id'), table_name='subcategories', schema='finance')
    op.drop_table('subcategories', schema='finance')
    op.drop_index('payment_method_idx', table_name='payment_methods', schema='finance')
    op.drop_index(op.f('ix_finance_payment_methods_user_id'), table_name='payment_methods', schema='finance')
    op.drop_index(op.f('ix_finance_payment_methods_label'), table_name='payment_methods', schema='finance')
    op.drop_index(op.f('ix_finance_payment_methods_id'), table_name='payment_methods', schema='finance')
    op.drop_table('payment_methods', schema='finance')
    op.drop_index(op.f('ix_finance_categories_user_id'), table_name='categories', schema='finance')
    op.drop_index(op.f('ix_finance_categories_label'), table_name='categories', schema='finance')
    op.drop_index(op.f('ix_finance_categories_id'), table_name='categories', schema='finance')
    op.drop_table('categories', schema='finance')
    op.drop_index('unique_account_with_subtype', table_name='accounts', schema='finance', postgresql_where=sa.text('subtype IS NOT NULL'))
    op.drop_index('unique_account_null_subtype', table_name='accounts', schema='finance', postgresql_where=sa.text('subtype IS NULL'))
    op.drop_index(op.f('ix_finance_accounts_id'), table_name='accounts', schema='finance')
    op.drop_index(op.f('ix_finance_accounts_financial_institution_id'), table_name='accounts', schema='finance')
    op.drop_table('accounts', schema='finance')
    op.drop_index(op.f('ix_finance_financial_institutions_name'), table_name='financial_institutions', schema='finance')
    op.drop_index(op.f('ix_finance_financial_institutions_id'), table_name='financial_institutions', schema='finance')
    op.drop_table('financial_institutions', schema='finance')
    op.drop_index('unique_currency_label_symbol', table_name='currencies', schema='finance')
    op.drop_index(op.f('ix_finance_currencies_symbol'), table_name='currencies', schema='finance')
    op.drop_index(op.f('ix_finance_currencies_label'), table_name='currencies', schema='finance')
    op.drop_index(op.f('ix_finance_currencies_id'), table_name='currencies', schema='finance')
    op.drop_table('currencies', schema='finance')
    # ### end Alembic commands ###
